### PR TITLE
Add FE/BE Capstones

### PR DESCRIPTION
**Pull request by s-espinosa**
@damwhit Can you take a look at this to see what you think/make sure the FE team is on board? My goal would be to put the capstones here and then remove them from the BE/FE pages.

@rwarbelow Let me know if you have any comments as well. I want to wait to see that FE is on board before merging, but also let me know if you have any comments on the way I incorporated it here.

Thanks to you both!

### CODE REVIEW

**Comment by damwhit** [comment]
I think this move makes a lot of sense. I'll double check with @LouisaBarrett to make sure she's on board before moving things over.

**Comment by damwhit** [comment]
Got the approval from Louisa, will have a pr up in the next couple of days!

**Comment by s-espinosa** [comment]
@damwhit Updated the link!

**Comment by damwhit** [comment]
@s-espinosa thanks for putting this together! Merging now!

**Pull request merged**
